# Generated by Django 3.1.3 on 2020-11-21 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 11, 9, 11, 255583), verbose_name='date published'),
        ),
    ]
