# Generated by Django 3.1.3 on 2020-11-28 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201128_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 17, 46, 56, 729301), verbose_name='date published'),
        ),
    ]
