# Generated by Django 3.1.3 on 2020-11-28 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201128_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 17, 55, 19, 836360), verbose_name='date published'),
        ),
    ]
