# Generated by Django 3.1.3 on 2020-11-30 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201130_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 15, 20, 20, 329311), verbose_name='date published'),
        ),
    ]
