# Generated by Django 3.1.3 on 2020-11-30 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201130_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 17, 50, 33, 135237), verbose_name='date published'),
        ),
    ]
